spring.application.name=_JosueDiaz_OsvaldoQuintanar_1B2B_backend
spring.config.import=optional:file:./.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
server.port=${SERVER_PORT:8080}
